# Site settings
title: Michael Anderson
# description: ""
# baseurl: "/home"
url: "https://mbanderson.github.io"

# Google Analytics
# google_analytics: UA—XXXXXXXX-X

# Author
author:
  name: Michael Anderson
  url: https://mbanderson.github.io
  email: mbanderson@ucla.edu

# Build settings
markdown: kramdown
truncation: 40
include:
  - _pages

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji # Emojis

# Permalinks
permalink: /:year-:month-:day/:title
paginate: 5

# Excludes
exclude: [Gemfile, Gemfile.lock, tale.gemspec]

# Disqus
# disqus: disqus-id
